### ISSUE TITLE
"si" wrongly "ŝi"

### ISSUE THREAD

**Issue by georgjaehnig** [martinrue/vocx#1]
"si" is spoken like "ŝi".

That's really a complicated bug and I can't see a solution, since there is no [si] sound in Polish :(

Same for "ci", like in "cifero".

Maybe switch to a Croatian engine?

**Comment by martinrue** [comment]
I think I've improved it where `si` and `ci` are within a word (but not in all cases), but `si` on its own appears to be more difficult.

Croatian isn't available in AWS Polly, so switching engine would be a lot more work, but may possibly be the best way to solve it.

**Comment by georgjaehnig** [comment]
Oh, nice improvement with `si` and `ci`!
